# Generated by Django 3.1 on 2021-07-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Categorie_Name',
            new_name='Category_Name',
        ),
    ]
